/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo1;


import static demo1.passenger.deleteAllRows;
import java.awt.Color;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class ticket extends javax.swing.JFrame {

    static void setModel(TableModel resultSetToTableModel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
ResultSet rs;

Connection con;
    public ticket() {
        initComponents(); 
        this.setLocationRelativeTo(null);
       // show_user();
       // show_user();
       try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","17cs107","sushanth107");
            String query="select * from TICKET";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(query);
            
            DefaultTableModel model=(DefaultTableModel) tabledata.getModel();
            deleteAllRows(model);
              boolean flag=false;
            while(rs.next())
            {
                
                String ticketid=rs.getString("ticket_id");
                String passid=rs.getString("passenger_id");
                String bookdate=rs.getString("book_date");
                String tdesc=rs.getString("ticket_description");
                
                if(flag==false)
               
                model.addRow(new Object[] {ticketid,passid,bookdate,tdesc});
                
            }
            
        }catch (SQLException | ClassNotFoundException ex) {
           
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static void deleteAllRows(final DefaultTableModel model){
         for(int i=model.getRowCount()-1;i>=0;i--)
         {
             model.removeRow(i);
         }
     }
    
    payment tablerowdata=new payment();
    

    /**
     *
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@localhost:1521:XEPU").createEntityManager();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ticket_id = new javax.swing.JTextField();
        p_id = new javax.swing.JTextField();
        book_date = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        pay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ticket_desc = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        jLabel7.setText("TICKET ID :");

        jLabel8.setText("PASSENGER ID :  ");

        jLabel9.setText("            BOOK DATE :");

        jLabel10.setText("TICKET DESCRIPTION :");

        ticket_id.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ticket_idMouseMoved(evt);
            }
        });
        ticket_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_idActionPerformed(evt);
            }
        });

        book_date.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                book_dateMouseMoved(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 255, 0));
        home.setText("home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 255, 0));
        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 255, 0));
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(0, 255, 0));
        view.setText("view");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TICKET DETAILS");

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ticket_id", "passenger_id", "book_date", "ticket_description"
            }
        ));
        tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabledata);

        pay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pay.setForeground(new java.awt.Color(255, 0, 0));
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Pictures\\project\\arrow.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        ticket_desc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- source-destination--", "mangalore-bangalore", "mangalore-mumbai", "mangalore-chennai", "mangalore-dehli" }));
        ticket_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_descActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(view))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(15, 15, 15))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(book_date)
                                    .addComponent(p_id, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(ticket_id, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(ticket_desc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(home)
                                .addGap(15, 15, 15)
                                .addComponent(submit)
                                .addGap(18, 18, 18)
                                .addComponent(clear)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticket_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(book_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticket_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(home)
                            .addComponent(submit)
                            .addComponent(clear))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        
        
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","17cs107","sushanth107");
            String query="select * from TICKET";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(query);
            
            DefaultTableModel model=(DefaultTableModel) tabledata.getModel();
            deleteAllRows(model);
              boolean flag=false;
            while(rs.next())
            {
                
                String ticketid=rs.getString("ticket_id");
                String passid=rs.getString("passenger_id");
                String bookdate=rs.getString("book_date");
                String tdesc=rs.getString("ticket_description");
                
                if(flag==false)
               
                model.addRow(new Object[] {ticketid,passid,bookdate,tdesc});
                
            }
            
            
        }catch (SQLException | ClassNotFoundException ex) {
           
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
       
        
                        
    }//GEN-LAST:event_viewActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
       sample s=new sample();
       s.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String id=ticket_id.getText();
        String pid=p_id.getText();
        String bookdate=book_date.getText();
        
        String tdesc=(String) ticket_desc.getSelectedItem();
          try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","17cs107","sushanth107");
            Statement stat=con.createStatement();
            String query="insert into TICKET(TICKET_ID,PASSENGER_ID,BOOK_DATE,TICKET_DESCRIPTION)values('"+id+"','"+pid+"','"+bookdate+"','"+tdesc+"')";
            stat.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null,"successfull");
            
           con.close();
            
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"enter all the fields");
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null,"enter all the fields");
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          
          
          
          try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","17cs107","sushanth107");
            String query="select * from TICKET";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(query);
            
            DefaultTableModel model=(DefaultTableModel) tabledata.getModel();
            deleteAllRows(model);
              boolean flag=false;
            while(rs.next())
            {
                
                String ticketid=rs.getString("ticket_id");
                String passid=rs.getString("passenger_id");
                String bookdate1=rs.getString("book_date");
                String tdesc1=rs.getString("ticket_description");
                
                if(flag==false)
               
                model.addRow(new Object[] {ticketid,passid,bookdate1,tdesc1});
                
            }
            
        }catch (SQLException | ClassNotFoundException ex) {
           
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        ticket_id.setText(null);
        p_id.setText(null);
        book_date.setText(null);
        //ticket_desc.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void tabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledataMouseClicked
        // TODO add your handling code here:
       pay.setText("payment");
        
    }//GEN-LAST:event_tabledataMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        // TODO add your handling code here:
        int index=tabledata.getSelectedRow();
        TableModel model=tabledata.getModel();
        String ticket_id=model.getValueAt(index, 0).toString();
        String passenger_id=model.getValueAt(index, 1).toString();
        String book_date=model.getValueAt(index, 2).toString();
        String ticket_description=model.getValueAt(index, 3).toString();
        tablerowdata.setVisible(true);
        tablerowdata.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        tablerowdata.t_id.setText(ticket_id);
        tablerowdata.p_id.setText(passenger_id);
        tablerowdata.book_date.setText(book_date);
        tablerowdata.ticket_desc.setText(ticket_description); 
        this.dispose();
        
        //String id=t_id.getText();
        //String pid=p_id.getText();
        //String bookdate=book_date.getText();
        
        //String tdesc=ticket_desc.getText();
        onlinepay p=new onlinepay();
        p.tid=ticket_id;
        p.pid=passenger_id;
        p.bdate=book_date;
        p.tdescp=ticket_description;
          
        
        
    }//GEN-LAST:event_payMouseClicked

    private void ticket_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_idActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","17cs107","sushanth107");
            String query="select TICKET_ID from TICKET";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(query);
            while(rs.next())
            {
            String ticketid=rs.getString("ticket_id");
            }
            String ticketid = null;
            ticket_id.setText(ticketid);
            
        
        
        
        }
        catch(Exception ex){
            
        }
        
    }//GEN-LAST:event_ticket_idActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        passenger pass=new passenger();
        pass.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ticket_idMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket_idMouseMoved
        // TODO add your handling code here:
         
        //this.setVisible(true);
    }//GEN-LAST:event_ticket_idMouseMoved

    private void book_dateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_dateMouseMoved
        // TODO add your handling code here:
       // book_date.setBackground(Color.yellow);
    }//GEN-LAST:event_book_dateMouseMoved

    private void ticket_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_descActionPerformed
        // TODO add your handling code here:
        String tdesc=(String) ticket_desc.getSelectedItem();
        if(tdesc.equals("-- source-destination--"))
        {
           JOptionPane.showMessageDialog(null,"select the source and destination");
        }
    }//GEN-LAST:event_ticket_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField book_date;
    private javax.swing.JButton clear;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField p_id;
    private javax.swing.JLabel pay;
    public javax.swing.JButton submit;
    private javax.swing.JTable tabledata;
    private javax.swing.JComboBox<String> ticket_desc;
    public javax.swing.JTextField ticket_id;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    
}
